
export const REQUEST_PRODUCTS_DATA = "REQUEST_PRODUCTS_DATA";
export const RECEIVED_PRODUCTS_DATA = "RECEIVED_PRODUCTS_DATA";
export const REQUEST_ADD_TO_CART = "REQUEST_ADD_TO_CART";
export const RECEIVED_ADD_TO_CART = "RECEIVED_ADD_TO_CART";
export const REQUEST_ADD_PRODUCT = "REQUEST_ADD_PRODUCT";
export const REQUEST_MINUS_PRODUCT = "REQUEST_MINUS_PRODUCT";
