export const REQUEST_BANNER_DATA = "REQUEST_BANNER_DATA";
export const RECEIVED_BANNER_DATA = "RECEIVED_BANNER_DATA";
export const REQUEST_CATEGORIES_DATA = "REQUEST_CATEGORIES_DATA";
export const RECEIVED_CATEGORIES_DATA = "RECEIVED_CATEGORIES_DATA";